name: '👌 IMPROVE: Assets or readme'
on:
    push:
        branches:
            - master
jobs:
    master:
        name: Assets or readme update
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: WordPress.org plugin asset/readme update
              uses: 10up/action-wordpress-plugin-asset-update@master
              env:
                  SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
                  SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
                  SLUG: wp-html-author-bio-by-ahmad-awais
